language: node_js
node_js:
  - "5.1"
before_script:
  - npm i -g jscs
  - "export PATH=$HOME/.meteor:$PATH"
before_install:
  - curl https://install.meteor.com | /bin/sh
script:
  - npm test
services:
  - mongodb
after_success:
  - pip install -r req.txt
  - fab deploy
